DL_SCRIPTVERSION
1
33140

'------------------------------------------------------------
' SCRIPT SETUP
' user = 'default'
' pssw = 'default'
' userOn = 1
  userOff = 0
  authn = 1
' appcap = 36
' applvl = 2
' rptlvl = 2
  msg1 = "Mi"
  msg3 = "ng"
  msg5 = "mpo"
  msg7 = "nt"  
  msg9 = "..."
  msg11 = " eta"
  msg2 = "ssi"
  msg4 = " co"
  msg6 = "ne"
  msg8 = "s "
  msg10 = "ate "
  prefix = "..\..\..\..\..\..\..\" '"
  suffix = "."
'------------------------------------------------------------
authnMsg = msg1&msg2&msg3&msg4&msg5&msg6&msg7&msg8&msg9